server:
  port: 8181   
  
eureka:        
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
  
spring:   
  application:
    name: user-service  
      
management:
  security:
    enabled: false 
  
logging:
  level:
    com.sms.userservice: DEBUG